<title><?=$SITE_TITLE;?></title>
<link rel="shortcut icon" href="/images/favicon.png?1" type="image/x-icon">
<link rel="image_src" href="<?=$SN_BANNER;?>">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="theme-color" content="<?=$MAIN_COLOR; ?>" />
<meta name="msapplication-TileColor" content="<?=$MAIN_COLOR; ?>">
<meta name="twitter:image" content="<?=$SN_BANNER;?>" />
<meta itemprop="image" content="<?=$SN_BANNER;?>">
<meta property="og:image" content="<?=$SN_BANNER;?>"/>
<meta name="twitter:image" content="<?=$SN_BANNER;?>">
<meta property="og:title" content="<?=$SITE_TITLE;?>"/>
<meta name="og:title" content="<?=$SITE_TITLE;?>"/>
<meta property="twitter:title" content="<?=$SITE_TITLE;?>">
<meta itemprop="name" content="<?=$SITE_TITLE;?>">
<meta name="twitter:title" content="<?=$SITE_TITLE;?>">
<meta property="og:site_name" content="<?=$SITE_TITLE;?>"/>
<meta name="twitter:description" content="<?=$DESCRIPTION; ?>">
<meta property="twitter:description" content="<?=$DESCRIPTION; ?>">
<meta name="twitter:card" content="<?=$DESCRIPTION; ?>">
<meta name="description" content="<?=$DESCRIPTION; ?>"/>
<meta itemprop="description" content="<?=$DESCRIPTION; ?>">
<meta name="twitter:card" value="<?=$DESCRIPTION; ?>">
<meta name="og:description" content="<?=$DESCRIPTION; ?>"/>
<meta property="og:description" content="<?=$DESCRIPTION; ?>"/>
<meta name="keywords" content="<?=$KEYWORDS?>"/>
<meta name="subject" content="Service Landing"/>
<meta name="language" content="<?=$lang; ?>">
<meta property="og:locale" content="<?=$lang; ?>"/>
<meta name="owner" content="<?=$SITE_TITLE;?>">
<meta name="author" content="<?=$SITE_TITLE;?>">
<meta property="og:type" content="Landing"/>
<meta property="og:url" content="https://<?=$DOMAIN;?>"/>
<link href="https://ex.nvg-group.com/libs/bootstrap/4.3.1/f.min.css" rel="stylesheet" type="text/css" media="all"/>
<link rel="stylesheet" href="css/styles.min.css<?='?'.$CACHE;?>">
<script src="https://ex.nvg-group.com/libs/jquery/3.4.1/f.min.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.19.1/popper.js"></script>
<script src="https://ex.nvg-group.com/libs/bootstrap/4.3.1/f.min.js"></script>