<title><?=$SITE_TITLE;?></title>
<link rel="shortcut icon" href="/images/favicon.png" type="image/x-icon">
<link rel="image_src" href="<?=$SN_BANNER;?>">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="theme-color" content="<?=$MAIN_COLOR; ?>" />
<meta name="msapplication-TileColor" content="<?=$MAIN_COLOR; ?>">
<meta name="twitter:image" content="<?=$SN_BANNER;?>" />
<meta itemprop="image" content="<?=$SN_BANNER;?>">
<meta property="og:image" content="<?=$SN_BANNER;?>"/>
<meta name="twitter:image" content="<?=$SN_BANNER;?>">
<meta property="og:title" content="<?=$SITE_TITLE;?>"/>
<meta name="og:title" content="<?=$SITE_TITLE;?>"/>
<meta property="twitter:title" content="<?=$SITE_TITLE;?>">
<meta itemprop="name" content="<?=$SITE_TITLE;?>">
<meta name="twitter:title" content="<?=$SITE_TITLE;?>">
<meta property="og:site_name" content="<?=$SITE_TITLE;?>"/>
<meta name="twitter:description" content="<?=$DESCRIPTION; ?>">
<meta property="twitter:description" content="<?=$DESCRIPTION; ?>">
<meta name="twitter:card" content="<?=$DESCRIPTION; ?>">
<meta name="description" content="<?=$DESCRIPTION; ?>"/>
<meta itemprop="description" content="<?=$DESCRIPTION; ?>">
<meta name="twitter:card" value="<?=$DESCRIPTION; ?>">
<meta name="og:description" content="<?=$DESCRIPTION; ?>"/>
<meta property="og:description" content="<?=$DESCRIPTION; ?>"/>
<meta name="keywords" content="<?=$KEYWORDS?>"/>
<meta name="subject" content="Service Landing"/>
<meta name="language" content="<?=$lang; ?>">
<meta property="og:locale" content="<?=$lang; ?>"/>
<meta name="owner" content="<?=$SITE_TITLE;?>">
<meta name="author" content="<?=$SITE_TITLE;?>">
<meta property="og:type" content="Landing"/>
<meta property="og:url" content="https://<?=$DOMAIN;?>"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<link href="https://ex.nvg-group.com/libs/mdb/4.19.1/bootstrap.min.css" rel="stylesheet" type="text/css" media="all"/>
<link href="https://ex.nvg-group.com/libs/mdb/4.19.1/mdb.min.css" rel="stylesheet" type="text/css" media="all"/>
<link href="https://ex.nvg-group.com/libs/mdb/4.19.1/modules/animations-extended.min.css" rel="stylesheet" type="text/css" media="all"/>
<link rel="stylesheet" href="css/styles.min.css<?='?'.$CACHE;?>">
<script src="https://ex.nvg-group.com/libs/mdb/4.19.1/jquery.min.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.19.1/popper.min.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.19.1/bootstrap.min.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.19.1/mdb.min.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.19.1/modules/animations-extended.min.js"></script>
<script src="https://ex.nvg-group.com/libs/mdb/4.19.1/modules/wow.min.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
   (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
   m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
   (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

   ym(69076681, "init", {
        clickmap:true,
        trackLinks:true,
        accurateTrackBounce:true,
        webvisor:true
   });
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/69076681" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-QQNJE42QRG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-QQNJE42QRG');
</script>