<div class="container pt-5 mt-3">
	<div class="row">
		<div class="col-md-5 text-main text-left">
			<h1 class="uk-heading-small">Coming soon</h1>
		</div>
		<div class="col-md-4"></div>
		<div class="col-md-3 text-right d-none d-md-block">
			<img class="logo" src="images/logo.svg?3">
		</div>
	</div>

	<div class="row my-3">
		<div class="col-md-9 text-light text-left">
			<p>
                <?=$__translations['d0'];?> <a href="https://drones-control.com" target="_blank" class="text-main"><?=$__translations['pp'];?> &#62;&#62;</a>
            </p>
            <p class="mt-4">
                <?=$__translations['pp2'];?> <a href="#" class="text-main"><?=$__translations['here'];?> &#62;&#62;</a></a>
            </p>
		</div>
	</div>


    <div class="my-5 text-center">
        <div>
            <a class="btn btn-main" href="https://nvg.li/dronesc_simulator" download><?=$__translations['download'];?> <?=$__translations['for'];?> Windows</a>
        </div>
        <div class="mt-3 text-light">
            <?=$__translations['download'];?> (v<?=$G_VERSION;?>) <span class="d-none"> <?=$__translations['for'];?> <a href="#" class="text-main">Mac</a> or <a href="#" class="text-main">Linux</a></span>
        </div>
    </div>

	<div class="pt-5">
		<div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/-q4RyP_Xsq8?autoplay=1&amp;showinfo=0&amp;rel=0&amp;modestbranding=1&playsinline=1&mute=1" allowfullscreen></iframe>
        </div>
	</div>

</div>