<div class="container pt-5 mt-3">
	<div class="row">
		<div class="col-md-3 text-main text-left">
			<h1 class="uk-heading-small">Coming soon</h1>
		</div>
		<div class="col-md-6"></div>
		<div class="col-md-3 text-right">
			<img src="images/logo.svg?0" width="67">
		</div>
	</div>

	<div class="row my-3">
		<div class="col-md-9 text-light text-left">
			<?=$__translations['d0'];?> <a href="https://service.drones-c.com" target="_blank" class="text-main"><?=$__translations['pp'];?> >></a>
		</div>
	</div>

	</div>
</div>